# Generated by Django 3.2.2 on 2021-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_podcast', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.FloatField(null=True)),
                ('Uploaded_time', models.DateTimeField()),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_song', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.FloatField(null=True)),
                ('Uploaded_time', models.DateTimeField()),
            ],
        ),
    ]
