# Generated by Django 3.2.2 on 2021-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_podcast_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_the_audiobook', models.CharField(max_length=100)),
                ('Duration_in_number_of_seconds', models.FloatField(null=True)),
                ('Uploaded_time', models.DateTimeField()),
                ('Author_of_the_title', models.CharField(max_length=100)),
                ('Participants', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
            ],
        ),
    ]
