# Generated by Django 3.2.2 on 2021-05-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audiobook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
